---

- name: Teardown Generated Files and Directories
  hosts: localhost
  connection: local

  vars:
    deploy_dir: "{{ playbook_dir }}"

  tasks:

  - name: Clear CRL Directory
    file:
      path: "{{ deploy_dir }}/crl"
      state: absent

  - name: Clear PKCS#12 Directory
    file:
      path: "{{ deploy_dir }}/pkcs12"
      state: absent

  - name: Clear CA Directory
    file:
      path: "{{ deploy_dir }}/ca"
      state: absent